SET GLOBAL LOCAL_INFILE=TRUE;
-- SHOW GLOBAL VARIABLES LIKE 'LOCAL_INFILE';

-- exited MySQL then started again with ```sudo mysql --local-infile=1```

LOAD DATA LOCAL INFILE 'Loading Data/clubs.csv' INTO TABLE clubs
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'Loading Data/players.csv' INTO TABLE players
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'Loading Data/outfield_players.csv' INTO TABLE outfield_players
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'Loading Data/goalkeepers.csv' INTO TABLE goalkeepers
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;